blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.PostListView.as_view(), name="blog-home" ),
    path('about/', views.about, name='blog-about'),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("post/new/", views.PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/update/", views.PostUpdateView.as_view(), name="post-update"), 
    path("post/<int:pk>/delete/", views.PostDeleteView.as_view(), name="post-delete"), 
    path("post/<int:pk>/comment/", views.CommentCreateView.as_view(), name="add-comment"),
    path("comment/<int:pk>/update/", views.CommentUpdateView.as_view(), name="comment-update"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
    path("like/<int:pk>/", views.likeView, name="like_post"),
    path("comment_like/<int:pk>/", views.commentLikeView, name="comment_like_post"),
]

cinebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('', include('movies.urls')),
    path('admin/', admin.site.urls),
    path("blog/", include('blog.urls')),
    path('users/', include('users.urls')),
    path('cinemas/', include('cinemas.urls')),
    path('showtimes/', include('showtimes.urls')),
    path('screeningrooms/', include('screeningrooms.urls')),
    path('bookings/', include('bookings.urls')),
    # JWT Auth paths
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    """Model representing a blog post."""

    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='blog_posts')

    def total_likes(self):
        """Return the total number of likes for this post."""
        return self.likes.count()
    
    def __str__(self):
        """String representation of the Post."""
        return self.title 

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this Post."""
        return reverse("post-detail", kwargs={"pk": self.pk})


class Comment(models.Model):
    """Model representing a comment on a blog post."""

    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='comment_likes')
    
    def is_author(self, user):
        """
        Determine if the given user is the author of this comment.
        """
        return self.author == user
    
    def total_comment_likes(self):
        """
        Return the total number of likes on this comment.
        """
        return self.likes.count()

    def __str__(self):
        """String representation of the Comment."""
        return f"Comment by {self.author.username} on {self.post.title}"

    def get_absolute_url(self):
        """Returns the URL to access a detail record for the Post associated with this Comment."""
        return reverse("post-detail", kwargs={"pk": self.post.pk})

movies/models.py
from django.db import models

class Movie(models.Model):
    title = models.CharField(max_length=255, verbose_name="Title")
    tmdb_id = models.IntegerField(unique=True, verbose_name="TMDb ID")
    director = models.CharField(max_length=255, verbose_name="Director")
    cast = models.TextField(verbose_name="Cast") 
    user_rating = models.FloatField(verbose_name="User Rating")
    trailer_link = models.URLField(verbose_name="Trailer Link")
    overview = models.TextField(verbose_name="Overview")
    release_date = models.DateField(verbose_name="Release Date")
    poster_path = models.URLField(verbose_name="Poster URL")
    original_language = models.CharField(max_length=10, verbose_name="Original Language")


    def __str__(self):
        return self.title

    def user_rating_stars(self):
        #Convert the user rating from TMDb to 0-5 scale
        rating_scaled = self.user_rating / 2 
        #Round the rating to the nearest 2 decimal places for display purposes
        rating_rounded = round(rating_scaled * 2) / 2
        return rating_rounded

    class Meta:
        verbose_name = "Movie"
        verbose_name_plural = "Movies"

showtimes/models.py
from django.db import models
from movies.models import Movie
from screeningrooms.models import ScreeningRoom
from django.utils import timezone
from django.apps import apps

class Showtime(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="Movie")
    screening_room = models.ForeignKey(ScreeningRoom, on_delete=models.CASCADE, verbose_name="Screening Room")
    showtime = models.DateTimeField(verbose_name="Showtime")

    def available_seats(self):
        SeatReservation = apps.get_model('bookings', 'SeatReservation')
        total_seats = self.screening_room.seats.count()
        reserved_seats = SeatReservation.objects.filter(showtime=self, is_reserved=True).count()
        return total_seats - reserved_seats

    def __str__(self):
        return f"{self.movie} at {self.showtime} in {self.screening_room}"

    def has_passed(self):
        """Checks if the showtime has already occurred."""
        return self.showtime < timezone.now()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.core.exceptions import PermissionDenied
from django import forms


def home(request):
    """View to render the home page with a list of posts."""
    context = {"posts": Post.objects.all()}
    return render(request, "blog/home.html", context)

def likeView(request, pk):
    post = get_object_or_404(Post, id=pk)
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        # The user already liked this post.
        post.likes.remove(request.user)
        liked = False
    else:
        # A new like was added.
        post.likes.add(request.user)
        liked = True
    # Redirect back to the post detail view.
    return HttpResponseRedirect(reverse('post-detail', args=[str(pk)]))

def commentLikeView(request, pk):
    comment = get_object_or_404(Comment, id=pk)
    user_id = request.user.id if request.user.is_authenticated else 'Anonymous'

    commnet_liked = False
    if comment.likes.filter(id=request.user.id).exists():
        # The user has already liked this comment.
        comment.likes.remove(request.user)
        commnet_liked = False
    else:
        # A new like on the comment was added.
        comment.likes.add(request.user)
        commnet_liked = True

    return HttpResponseRedirect(reverse('post-detail', args=[str(comment.post.pk)]))

class PostListView(ListView):
    """View to display a list of blog posts."""

    model = Post
    template_name = "blog/home.html"
    context_object_name = "posts"
    ordering = ["-date_posted"]
    paginate_by = 5


class PostDetailView(DetailView):
    model = Post


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object 
        comments_list = Comment.objects.filter(post=post).order_by("-date_posted")

        # Paginate the comments list
        page = self.request.GET.get('page', 1)
        paginator = Paginator(comments_list, 5)  # Show 5 comments per page
        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            comments = paginator.page(1)
        except EmptyPage:
            comments = paginator.page(paginator.num_pages)

        liked = post.likes.filter(id=self.request.user.id).exists() if self.request.user.is_authenticated else False

        for comment in comments:
            comment.user_has_liked = comment.likes.filter(id=self.request.user.id).exists()

        context.update({
            'comments': comments,
            'total_likes': post.likes.count(),
            'liked': liked,
            'page_obj': comments,
        })

        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    """View to create a new blog post."""

    model = Post
    fields = ["title", "content"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """View to update an existing blog post."""

    model = Post
    fields = ["title", "content"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """View to delete a blog post."""

    model = Post
    success_url = reverse_lazy("blog-home")

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class CommentCreateView(LoginRequiredMixin, CreateView):
    """View to create a new comment on a blog post."""

    model = Comment
    fields = ["content"]
    template_name = "blog/add_comment.html"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['content'].widget = forms.Textarea(attrs={
            'rows': 8,
            'style': 'resize:none;',  
            'placeholder': 'Write your comment here...'
        })
        form.fields['content'].label = ''
        return form

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = get_object_or_404(Post, pk=self.kwargs["pk"])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("post-detail", kwargs={"pk": self.kwargs["pk"]})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        context['post_detail'] = {
            'author_profile_image': post.author.profile.image.url,
            'author_username': post.author.username,
            'date_posted': post.date_posted,
            'title': post.title,
            'content': post.content
        }
        return context



class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    fields = ["content"]
    template_name = "blog/comment_update.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author

    def get_success_url(self):
        return reverse_lazy("post-detail", kwargs={"pk": self.object.post.pk})

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = "blog/comment_confirm_delete.html"

    def test_func(self):
        """
        Ensure only the comment author can delete the comment.
        """
        comment = self.get_object()
        if self.request.user != comment.author:
            raise PermissionDenied("You are not allowed to delete this comment.")
        return True

    def get_success_url(self):
        """
        Redirect to the associated post's detail page after deletion.
        """
        return reverse_lazy("post-detail", kwargs={"pk": self.object.post.pk})



def about(request):
    """
    View to display the about page.
    """
    return render(request, 'blog/about.html', {'title': 'About'})

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <h1>About MovieTicket</h1>
      <p>MovieTicket is an online platform for buying tickets for movie showtimes. We offer a wide range of cinemas, screening rooms, and showtimes to choose from. Our goal is to make the movie-going experience as convenient and enjoyable as possible.</p>
      <p>We also have a blog where we post articles about movies, cinema, and entertainment. Our blog is a great resource for movie enthusiasts and anyone looking for the latest news and trends in the movie industry.</p>
      <h2>Contact Us</h2>
      <p>If you have any questions or concerns, please don't hesitate to contact us:</p>
      <ul>
        <li>Email: <a href="mailto:info@movieticket.com">info@movieticket.com</a></li>
        <li>Phone: (123) 456-7890</li>
        <li>Address: 123 Main St, Anytown, USA</li>
      </ul>
    </div>
    <div class="col-md-6">
      <img src="{% static 'images/assets/cinema.jpg' %}" alt="Cinema" class="img-fluid">
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/add_comment.html
{% extends "blog/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="d-flex align-items-center justify-content-center">
    <div class="card w-100 w-md-75 w-lg-50 content-section">
        <div class="card-body">
            {% if post_detail %}
            <img class="img-fluid rounded  article-img " src="{{ post_detail.author_profile_image }}"
                alt="{{ post_detail.author_username }}">
            <h4 class="text-center">Comment on "{{ post_detail.title }}"</h4>
            <p class="text-center">By: {{ post_detail.author_username }} on {{ post_detail.date_posted|date:'dS, F, Y' }}</p>
            <p>{{ post_detail.content }}</p>
            {% endif %}
            <h4 class="mt-4">Add a Comment:</h4>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Post Comment</button>
                    <button class="btn btn-danger" type="button" onclick="history.back()">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- Font Awesome Cnd -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  {% if title %}
  <title>MovieTicket - {{ title }}</title>
  {% else %}
  <title>MovieTicket</title>
  {% endif %}
</head>

<body class="d-flex flex-column min-vh-100">
  <header>
    <nav class="navbar navbar-expand-lg bg-black fixed-top ">
      <div class="container-fluid ">
        <a class="navbar-brand mx-5  logo text-white" href="{% url 'movie_list' %}"><span class="logo">M</span>ovie<span class="logo">T</span>icket</a>
        <button class="navbar-toggler bg-white text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarToggle">
          <div class="navbar-nav me-auto">
            <a class="nav-item nav-link" aria-current="page" href="{% url 'movie_list' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'showtime_list' %}">Showtimes</a>
            <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
            <a class="nav-item nav-link" href="{% url 'blog-home' %}">Blog</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav ms-auto" >
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
            {% if user.is_staff or user.is_superuser %}
            <!-- Link to the admin page or a custom admin dashboard if you have one -->
            <a class="nav-item nav-link" href="{% url 'admin_dashboard' %}">Admin Page</a>
            {% endif %}
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container flex-grow-1 mt-5">
    <div class="row my-5">
      <div>
        {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% elif message.tags == 'success' %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
      </div>
    </div>
  </main>
  <footer class="container-fluid">
    <div class="row p-5 pb-2 bg-black text-white text-center">
      <div class="col-xs-12 col-md-6 col-lg-3">
        <p class="h3"><a class="text-white text-decoration-none" href="{% url 'movie_list' %}"><span class="text-danger">M</span>ovie<span class="text-danger">T</span>icket</a></p>
        <p>
          Ireland's leading movie ticket platform.
        </p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-3">
        <p class="h4 mb-3 border-bottom border-white">Info</p>
        <div class="mb-2">
          <a class="text-white text-decoration-none" href="#"><small>FAQs</small></a>
        </div>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-3">
        <p class="h4 mb-3 border-bottom border-white">Links</p>
        <div class="mb-2">
          <a class="text-white text-decoration-none" href="#"><small>Terms & Conditions</small></a>
        </div>
        <div class="mb-2">
          <a class="text-white text-decoration-none" href="#"><small>Privacy Policy</small></a>
        </div>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-3 border-1  ">
        <p class="h4 mb-3 border-bottom border-white">Contact</p>
        <div class="mb-2">
          <a class="text-white text-decoration-none" href="#"><small>FAQs</small></a>
        </div>
        <div class="mb-2">
          <a class="text-white text-decoration-none" href="#"><small>Contact Form</small></a>
        </div>
      </div>
      <div class="col-12 border-1  border-top border-white p-3 ">
        <a class="text-white me-2 me-md-3 github" target="_blank" href="https://github.com/Pedrolivares1980"><i class="fa-brands fa-github"></i></a>
        <a class="text-white me-2 me-md-3 whatsapp" target="_blank" href="https://api.whatsapp.com/send?phone=353899895252"><i class="fa-brands fa-whatsapp"></i></a>
        <a class="text-white me-2 me-md-3 youtube" target="_blank" href="https://www.youtube.com/"><i class="fa-brands fa-youtube"></i></a>
        <a class="text-white gmail" target="_blank" href="mailto:pedr.olivares80@gmail.com"><i class="fa-regular fa-envelope"></i></a>
      </div>
      <div class="col-12 border-1  border-top border-white p-4 pb-1">
        <p><small>Copyriht &copy; <script>document.write(new Date().getFullYear());</script> All Rights Reserved</small></p>
      </div>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>

  <script src="{% static 'js/base.js' %}" ></script>
  <!-- Additional Scripts -->
  {% block extra_js %}{% endblock %}
</body>

</html>

blog/templates/blog/comment_confirm_delete.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
	<h2>Are you sure you want to delete this comment?</h2>
	<form method="post">
		{% csrf_token %}
		<div class="mt-3">
			<button type="submit" class="btn btn-danger">Yes, delete comment</button>
			<a href="{% url 'post-detail' object.post.pk %}" class="btn btn-success">Cancel</a>
		</div>
	</form>
</div>
{% endblock content %}

blog/templates/blog/comment_thread.html
{% for comment in comments %}
<div class="custom-comment mb-3">
    <div class="row g-0">
        <!-- User information -->
        <div class="col-12 col-md-4  p-2">
            <img class="img-fluid rounded mx-auto my-2 d-block article-img  " src="{{ comment.author.profile.image.url }}" alt="User Image" style="width: 80px;">
            <div class="text-center mt-2">
                <h5>{{ comment.author.username }}</h5>
                <small class="text-muted">{{ comment.date_posted|date:"d M, Y" }}</small>
            </div>
        </div>
        
        <!-- Comment section -->
        <div class="col-12 col-md-8 p-2 ">
            <p>{{ comment.content }}</p>
        </div>
        
        <!-- Comment Actions -->
        <div class="col-12 p-2">
            <div class="d-md-flex justify-content-md-center align-items-center">
                <div class="mb-2 mb-md-0">
                    {% if user.is_authenticated %}
                    <form action="{% url 'comment_like_post' comment.pk %}" method="POST" class="d-flex align-items-center">
                        {% csrf_token %}
                        {% if comment.user_has_liked %}
                            <button type="submit" name="comment_id" value="{{ comment.id }}" class="btn btn-danger btn-sm me-2"><i class="bi bi-hand-thumbs-down-fill">Unlike</i></button>
                        {% else %}
                            <button type="submit" name="comment_id" value="{{ comment.id }}" class="btn btn-primary btn-sm me-2"><i class="bi bi-hand-thumbs-up-fill">Like</i></button>
                        {% endif %}
                        <span>{{ comment.likes.count }} likes</span>
                    </form>
                    {% else %}
                    <a href="{% url 'login' %}" class="text-danger">Login to like</a>
                    {% endif %}
                </div>
                
                {% if comment.author == user %}
                <div class="ms-md-3 d-flex justify-content-center gap-2">
                    <a href="{% url 'comment-update' comment.id %}" class="btn btn-success btn-sm">Edit</a>
                    <a href="{% url 'comment-delete' comment.id %}" class="btn btn-danger btn-sm">Delete</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}

blog/templates/blog/comment_update.html
{% extends "blog/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-3 ">
    <div class="custom-comment">
        <div class="comment-body">
            <h2>Update Comment</h2>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Update Comment</button>
                <button class="btn btn-danger" type="button" onclick="history.back()">Cancel</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

<div class="container d-flex flex-column min-vh-100">
  <div class="row g-3">
    <!-- Link Section -->
    <div class="col-12 col-md-4 order-md-2 mb-3">
      <div class="links-section p-3 rounded">
        <h3 class="text-center">CineBook Blog</h3>
        <div class="d-grid gap-2">
          {% if user.is_authenticated %}
          <a href="{% url 'post-create' %}" class="btn btn-primary">New Post</a>
          {% endif %}
          <a href="{% url 'blog-home' %}" class="btn btn-primary">Latest Posts</a>
        </div>
      </div>
    </div>
    
    <!-- Posts Section -->
    <div class="col-12 col-md-8 order-md-1">
      {% for post in posts %}
      <article class="media content-section p-3 rounded mb-3">
        <img class=" img-fluid rounded ms-2 article-img" src="{{ post.author.profile.image.url }}">
        <div class="media-body">
          <div class="article-metadata text-center">
            <p class="mr-2 mt-2">by {{ post.author }}</p>
            <small>{{ post.date_posted|date:'dS, F, Y' }}</small>
          </div>
          <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content|truncatewords:20 }}</p>
        </div>
      </article>
      {% endfor %}
    </div>
  </div>
  
  <!-- Pagination -->
  {% if page_obj.paginator.num_pages > 1 %}
  <div class="row">
    <div class="col-12 mt-3">
      <nav aria-label="Pagination" class="d-flex justify-content-center">
        <ul class="pagination justify-content-center  mt-4">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="btn btn-primary" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="First">First</a>
      </li>
      <li class="page-item">
        <a class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="Previous">Previous</a>
      </li>
      {% endif %}
      <li class="page-item disabled">
        <span class="btn btn-primary">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
      </li>
      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="Next">Next</a>
      </li>
      <li class="page-item">
        <a class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="Last">Last</a>
      </li>
      {% endif %}
      </ul>
      </nav>
    </div>
  </div>
  {% endif %}
</div>

{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="content-section d-flex align-items-center justify-content-center">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the post "{{ object.title}}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-sec" href="{% url 'post-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section ">
  <form method="POST" class="w-100 w-md-75 w-lg-50 mx-auto my-4 border border-3 border-black rounded">
    {% csrf_token %}
    <fieldset class="form-group p-3">
      <legend class="border-bottom mb-4 text-center">Blog Post</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="d-flex align-items-center justify-content-center p-3">
      <button class="btn btn-primary me-2" type="submit">Post</button>
      <button class="btn btn-danger" type="button" onclick="history.back()">Cancel</button>
    </div>
  </form>
</div>
{% endblock content %}