blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.PostListView.as_view(), name="blog-home" ),
    path('about/', views.about, name='blog-about'),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("post/new/", views.PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/update/", views.PostUpdateView.as_view(), name="post-update"), 
    path("post/<int:pk>/delete/", views.PostDeleteView.as_view(), name="post-delete"), 
    path("post/<int:pk>/comment/", views.CommentCreateView.as_view(), name="add-comment"),
    path("comment/<int:pk>/update/", views.CommentUpdateView.as_view(), name="comment-update"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
    path("like/<int:pk>/", views.likeView, name="like_post"),
    path("comment_like/<int:pk>/", views.commentLikeView, name="comment_like_post"),
]

cinebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('', include('movies.urls')),
    path('admin/', admin.site.urls),
    path("blog/", include('blog.urls')),
    path('users/', include('users.urls')),
    path('cinemas/', include('cinemas.urls')),
    path('showtimes/', include('showtimes.urls')),
    path('screeningrooms/', include('screeningrooms.urls')),
    path('bookings/', include('bookings.urls')),
    # JWT Auth paths
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

showtimes/urls.py
from django.urls import path
from .views import ShowtimeListView, ShowtimeCreateView, ShowtimeUpdateView, ShowtimeDeleteView

urlpatterns = [
    path('', ShowtimeListView.as_view(), name='showtime_list'),
    path('create/', ShowtimeCreateView.as_view(), name='showtime_create'),
    path('update/<int:pk>/', ShowtimeUpdateView.as_view(), name='showtime_update'),
    path('delete/<int:pk>/', ShowtimeDeleteView.as_view(), name='showtime_delete'),
]

showtimes/models.py
from django.db import models
from movies.models import Movie
from screeningrooms.models import ScreeningRoom
from django.utils import timezone
from django.apps import apps

class Showtime(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="Movie")
    screening_room = models.ForeignKey(ScreeningRoom, on_delete=models.CASCADE, verbose_name="Screening Room")
    showtime = models.DateTimeField(verbose_name="Showtime")

    def available_seats(self):
        SeatReservation = apps.get_model('bookings', 'SeatReservation')
        total_seats = self.screening_room.seats.count()
        reserved_seats = SeatReservation.objects.filter(showtime=self, is_reserved=True).count()
        return total_seats - reserved_seats

    def __str__(self):
        return f"{self.movie} at {self.showtime} in {self.screening_room}"

    def has_passed(self):
        """Checks if the showtime has already occurred."""
        return self.showtime < timezone.now()

showtimes/forms.py
from django import forms
from .models import  ScreeningRoom, Movie, Showtime
from cinemas.models import Cinema
from django.utils import timezone

class ShowtimeForm(forms.ModelForm):
    class Meta:
        model = Showtime
        fields = '__all__'
        widgets = {
            'showtime': forms.DateTimeInput(attrs={'type': 'datetime-local'}, format='%d-%m-%YT%H:%M'),
        }

    
    def __init__(self, *args, **kwargs):
        super(ShowtimeForm, self).__init__(*args, **kwargs)
        self.fields['showtime'].input_formats = ('%d-%m-%YT%H:%M',)

class ShowtimeFilterForm(forms.Form):
    cinema = forms.ModelChoiceField(queryset=Cinema.objects.all(), required=False, label="Cinema")
    screening_room = forms.ModelChoiceField(queryset=ScreeningRoom.objects.all(), required=False, label="Screening Room")
    movie = forms.ModelChoiceField(queryset=Movie.objects.none(), required=False, label="Movie")
    start_date = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}), label="Start Date")
    end_date = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}), label="End Date")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['movie'].queryset = Movie.objects.filter(
            showtime__showtime__gte=timezone.now()
        ).distinct()

showtimes/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import ShowtimeForm
from django.urls import reverse_lazy
from .models import Showtime
from .forms import ShowtimeFilterForm
from django.utils import timezone


class StaffRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff or self.request.user.is_superuser

class ShowtimeCreateView(StaffRequiredMixin, CreateView):
    model = Showtime
    form_class = ShowtimeForm 
    template_name = 'showtimes/showtime_form.html'
    success_url = reverse_lazy('admin_dashboard')

class ShowtimeUpdateView(StaffRequiredMixin, UpdateView):
    model = Showtime
    form_class = ShowtimeForm 
    template_name = 'showtimes/showtime_form.html'
    success_url = reverse_lazy('admin_dashboard')

class ShowtimeDeleteView(StaffRequiredMixin, DeleteView):
    model = Showtime
    template_name = 'showtimes/showtime_confirm_delete.html'
    success_url = reverse_lazy('admin_dashboard')

class ShowtimeListView(ListView):
    model = Showtime
    template_name = 'showtimes/showtime_list.html'
    context_object_name = 'showtimes'
    paginate_by = 6 

    def get_queryset(self):
        queryset = Showtime.objects.filter(showtime__gte=timezone.now()).order_by('showtime')

        form = ShowtimeFilterForm(self.request.GET)
        if form.is_valid():
            cinema = form.cleaned_data.get('cinema')
            screening_room = form.cleaned_data.get('screening_room')
            movie = form.cleaned_data.get('movie')
            start_date = form.cleaned_data.get('start_date')
            end_date = form.cleaned_data.get('end_date')

            if cinema:
                queryset = queryset.filter(screening_room__cinema=cinema)
            if screening_room:
                queryset = queryset.filter(screening_room=screening_room)
            if movie:
                queryset = queryset.filter(movie=movie)
            if start_date:
                queryset = queryset.filter(showtime__gte=start_date)
            if end_date:
                queryset = queryset.filter(showtime__lte=end_date)

        return queryset
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        showtimes = context['showtimes']
        
        showtimes_with_seat_info = [
            {
                'showtime': showtime,
                'total_seats': showtime.screening_room.seats.count(),
                'available_seats': showtime.available_seats()
            }
            for showtime in showtimes
        ]
        
        context['showtimes_with_seat_info'] = showtimes_with_seat_info
        context['filter_form'] = ShowtimeFilterForm(self.request.GET)
        return context

showtimes/templates/showtimes/showtime_confirm_delete.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="custom_container_delete">
        <h2>Confirm Delete</h2>
        <p class="my-5 w-50 text-center">
            Are you sure you want to delete:<br>
            "<strong>{{ object.movie.title }}</strong>"<br>
            in <strong>{{ object.screening_room.cinema.name }}</strong>-<strong>{{ object.screening_room.name }}</strong><br>
            at <strong>{{ object.showtime|date:"d-m-Y" }}</strong> at <strong>{{ object.showtime|time:"H:i" }}</strong>
        </p>
        <div class="d-flex justify-content-center gap-3 mt-5">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Yes, delete</button>
                <a href="{% url 'admin_dashboard' %}" class="btn btn-success">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

showtimes/templates/showtimes/showtime_form.html
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container mt-4">
    <h2 class="text-center mb-3">Add Showtime Form</h2>
    <div class="d-flex justify-content-center custom_container">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-flex justify-content-center gap-3 mt-3">
                <button type="submit" class="btn btn-primary">Add Showtime</button>
                <a href="{% url 'admin_dashboard' %}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

showtimes/templates/showtimes/showtime_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<!-- Section Title -->
<h2 class="text-center my-4">Upcoming Showtimes</h2>

<div class="text-center mb-3">
    <button class="btn btn-success mb-3" type="button" id="toggle-filters">Filters</button>
</div>

<div class="container border border-black" id="filter-form-container" style="display: none;">
    <!-- Filters -->
    <form method="get" class="my-4 p-2">
        <div class="d-flex flex-column flex-md-row justify-content-around align-items-center gap-2 p-2">
            <div class="mb-3 mb-md-0">
                <label for="id_cinema" class="form-label d-block text-center">Cinema</label>
                {{ filter_form.cinema }}
            </div>
            <div class="mb-3 mb-md-0">
                <label for="id_screening_room" class="form-label d-block text-center">Screening Room</label>
                {{ filter_form.screening_room }}
            </div>
            <div class="mb-3 mb-md-0">
                <label for="id_movie" class="form-label d-block text-center">Movie</label>
                <div class="input-wrapper">
                    {{ filter_form.movie }}
                </div>
            </div>
        </div>
        <div class="d-flex flex-column flex-md-row justify-content-around align-items-center mt-3">
            <div class="mb-3 mb-md-0">
                <label for="id_start_date" class="form-label d-block text-center">Start Date</label>
                {{ filter_form.start_date }}
            </div>
            <div class="mb-3 mb-md-0">
                <label for="id_end_date" class="form-label d-block text-center">End Date</label>
                {{ filter_form.end_date }}
            </div>
        </div>
        <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary">Filter</button>
            <a href="{% url 'showtime_list' %}" class="btn btn-danger">Clear Filters</a>
        </div>
    </form>
</div>

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4 bg-info">
        {% for item in showtimes_with_seat_info %}
        <div class="col p-2 pb-4">
            <div class="card h-100 ">
                {% if item.showtime.movie.poster_path %}
                <img src="{{ item.showtime.movie.poster_path }}" class="card-img-top"
                    alt="{{ item.showtime.movie.title }} poster">
                {% endif %}
                <div class="card-body text-center">
                    <h5 class="card-title">{{ item.showtime.movie.title }}</h5>
                    <p class="card-text">
                        <strong>Cinema:</strong> {{ item.showtime.screening_room.cinema.name }}<br>
                        <strong>Screening Room:</strong> {{ item.showtime.screening_room.name }}<br>
                        <strong>Time:</strong> {{ item.showtime.showtime|date:"d M Y H:i" }}<br>
                        <strong>Total Seats:</strong> {{ item.total_seats }}<br>
                        <strong>Available Seats:</strong> {{ item.available_seats }}
                    </p>
                </div>
                <div class="card-footer text-center my-2">
                    <a href="{% url 'movie_detail' item.showtime.movie.id %}" class="btn btn-success mt-2">Movie
                        Details</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'create_booking' item.showtime.id %}" class="btn btn-primary mt-2">Book Now</a>
                    {% else %}
                    <a href="{% url 'login' %}" class="btn btn-primary mt-2">Login to Book</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% empty %}
        <div class="container bg-info-subtle">
            <div class="row justify-content-center align-items-center">
                <div class="col-md-6 text-center">
                    <div class="alert-info custom-alert-container" role="alert">
                        <p class="py-3">We are sorry but at this time there is no showtime available that meets your
                            requirements. Make a new search and we are sure we will be able to satisfy you.</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Pagination -->
    {% if page_obj.paginator.num_pages > 1 %}
    <div class="row">
        <div class="col-12 mt-3">
            <nav aria-label="Pagination" class="d-flex justify-content-center">
                <ul class="pagination justify-content-center  mt-4">
                    {% if page_obj.has_previous %}
                    <li class="page-item m-1">
                        <a class="btn btn-primary" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                            aria-label="First">First</a>
                    </li>
                    <li class="page-item m-1">
                        <a class="btn btn-primary"
                            href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                            aria-label="Previous">Previous</a>
                    </li>
                    {% endif %}
                    <li class="page-item disabled m-1">
                        <span class="btn btn-primary custom_pagination">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
                    </li>
                    {% if page_obj.has_next %}
                    <li class="page-item m-1">
                        <a class="btn btn-primary"
                            href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                            aria-label="Next">Next</a>
                    </li>
                    <li class="page-item m-1">
                        <a class="btn btn-primary"
                            href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                            aria-label="Last">Last</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
    {% endif %}
</div>

<script src="{% static 'js/filters.js' %}"></script>

{% endblock %}